name: emdad
description: emdad.

publish_to: 'none'

version: 1.1.14+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  provider: ^6.0.3

  connectivity: ^3.0.6
  dio: ^4.0.6
  http: ^0.13.4
  freezed: ^2.0.3+1
  shared_preferences: ^0.5.6+3
  fancy_bottom_navigation: ^0.3.3
  carousel_slider: ^4.1.1
  shimmer: ^2.0.0
  url_launcher: ^6.1.3
  image_picker: ^0.8.5+3
  webview_flutter: ^3.0.4
  flutter_html: ^3.0.0-alpha.5
  share: ^2.0.4
  photo_view: ^0.14.0
  package_info: ^2.0.2
  firebase_core: ^1.24.0
  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^9.6.0
  path_provider: ^2.0.11
  google_sign_in: ^5.3.3
  flutter_facebook_auth: ^4.3.4+2
  flutter_svg: ^1.1.0
  phone_number: ^0.12.0+2
  country_code_picker: ^2.0.2
  pin_code_fields: ^7.4.0
  google_maps_flutter: ^2.1.7
  flutter_google_places: ^0.3.0
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  flutter_typeahead: ^4.0.0
  marquee: ^2.2.3
  flutter_rating_bar: ^4.0.1
  google_mobile_ads: ^1.2.0
  cached_network_image: ^3.2.1
  flutter_advanced_switch: ^3.0.1
  modal_progress_hud_nsn: ^0.2.1
  sizer: ^2.0.15
  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  im_stepper: ^1.0.1+1
  status_change: ^2.0.0
  flutter_staggered_grid_view: ^0.6.1
  staggered_grid_view_flutter: ^0.0.4
  firebase_auth: ^3.11.2
  location: ^2.3.5
  getwidget:

dependency_overrides:
  google_api_headers: ^1.3.0-dev.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 600
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 500
